#! /bin/bash
#PBS -A incite21 
#PBS -N model_sim_run
#PBS -m e
#PBS -j oe
#PBS -l walltime=0:3:00
#PBS -l mppwidth=4
#PBS -q debug
#PBS -S /bin/bash

cd $PBS_O_WORKDIR
umask=0222
$$SCRATCH/ips/bin/ips --config=$SCRATCH/code_camp/model_sim_mcmd_sveta.conf --platform=$SCRATCH/ips/franklin.conf --log=py.log  --debug

