SIM_NAME = simpleensembleinstance
SIM_ROOT = $PWD
LOG_FILE = log
LOG_LEVEL = INFO
SIMULATION_MODE = NORMAL

[PORTS]
    NAMES = DRIVER WORKER
    [[DRIVER]]
        IMPLEMENTATION = instance_driver

    [[WORKER]]
        IMPLEMENTATION = instance_component

[instance_driver]
    CLASS = DRIVER
    SUB_CLASS =
    NAME = InstanceDriver
    NPROC = 1
    BIN_PATH =
    INPUT_FILES =
    OUTPUT_FILES =
    SCRIPT = $PWD/instance_driver.py
    MODULE =

[instance_component]
    CLASS = WORKER
    SUB_CLASS =
    NAME = InstanceComponent
    NPROC = 1
    BIN_PATH =
    INPUT_FILES =
    OUTPUT_FILES =
    SCRIPT = $PWD/instance_component.py
    MODULE =
    # These are the variables that will have values substituted for each instance.
    # Note that not all the variables need to be declared here, as 'A', which is used
    # in the CSV file.  Also, the use of '?' is not mandatory, but is an optional way
    # to emphasize that these values will be provided externally.  You can leave them
    # blank, as is the case with 'B' or, again, not even declare them here.
    B =
    C = ?
