repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: check-yaml
      args: ['--unsafe']
    - id: check-toml
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.0
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  #- repo: https://github.com/astral-sh/uv-pre-commit
    #rev: 0.6.11
    #hooks:
      #- id: uv-lock
      #- id: uv-export
  #- repo: local
    #hooks:
      #- id: mypy
        #name: MyPy
        #description: use MyPy for static type checking
        #entry: pdm run mypy intersect_registry_service
        #pass_filenames: false
        #language: system
  #- repo: https://github.com/codespell-project/codespell
    # Configuration for codespell is in pyproject.toml
    #rev: v2.3.0
    #hooks:
    #- id: codespell
      #additional_dependencies:
      #- tomli
