version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

sphinx:
  builder: html
  configuration: doc/conf.py
  fail_on_warning: true

formats: all

python:
  install:
    - requirements: doc/requirements.txt
