# same as NERSC Cori module python/3.8-anaconda-2020.11
name: ips_test_dask_2.30
channels:
- conda-forge
dependencies:
- pytest-cov<4
- pytest-timeout
- psutil
- mpi4py
- openmpi
- dask=2.30.0
- click<8
- coverage!=6.3
- flask=2.0.3
