#! /bin/bash
#PBS -A m876 
#PBS -N model_sim
#PBS -m e
#PBS -j oe
#PBS -l walltime=0:3:00
#PBS -l mppwidth=4
#PBS -q debug 
#PBS -S /bin/bash

IPS_ROOT=$SCRATCH/ips
cd $PBS_O_WORKDIR
umask=0222

$IPS_ROOT/bin/ips --config=restart_12_sec.config --platform=$IPS_ROOT/franklin.conf --log=restart_12_sec.config_pbs.log
