# Platform config to run this example on localhost
MPIRUN = eval
NODE_DETECTION = manual
PROCS_PER_NODE = 8
CORES_PER_NODE = 8
SOCKETS_PER_NODE = 1
NODE_ALLOCATION_MODE =  shared
HOST = localhost
USE_PORTAL = False
SCRATCH =


