SIM_NAME = simpleensembleinstance
SIM_ROOT = $PWD
LOG_FILE = log
LOG_LEVEL = INFO
SIMULATION_MODE = NORMAL

[PORTS]
    NAMES = DRIVER WORKER
    [[DRIVER]]
        IMPLEMENTATION = instance_driver

    [[WORKER]]
        IMPLEMENTATION = instance_component

[instance_driver]
    CLASS = DRIVER
    SUB_CLASS =
    NAME = InstanceDriver
    NPROC = 1
    BIN_PATH =
    INPUT_FILES =
    OUTPUT_FILES =
    SCRIPT = $PWD/instance_driver.py
    MODULE =

[instance_component]
    CLASS = WORKER
    SUB_CLASS =
    NAME = InstanceComponent
    NPROC = 2
    BIN_PATH =
    INPUT_FILES =
    OUTPUT_FILES =
    SCRIPT = $PWD/instance_component.py
    MODULE =
    # These are the variables that will have values substituted for each instance.
    # The ? are important to indicate that these are to be filled in.
    A = ?
    B = ?
    C = ?
