# NEED TO ADD:
# - RUN_ID
# - SIM_ROOT
# - SIM_NAME
# - PARENT_PORTAL_RUNID
# - PORTAL_URL
# - PORTAL_API_KEY

LOG_FILE = $SIM_ROOT/child_sim.log
LOG_LEVEL = DEBUG
SIMULATION_MODE = NORMAL
RUN_COMMENT = From PC
TAG = tag
INPUT_DIR = $PWD/input_dir/

[PORTS]
    NAMES = DRIVER

    [[DRIVER]]
        IMPLEMENTATION = driver

[driver]
    CLASS = DRIVER
    SUB_CLASS =
    NAME = ChildWorkflowDriver
    NPROC = 1
    BIN_PATH =
    OUTPUT_FILES =
    INPUT_FILES =
    SCRIPT = $PWD/child_workflow_driver.py

[TIME_LOOP]
    MODE = REGULAR
    START = 1
    FINISH = 30
    NSTEP = 30
