SIM_NAME = simpleensemble
SIM_ROOT = $PWD
LOG_FILE = log
LOG_LEVEL = INFO
SIMULATION_MODE = NORMAL

[PORTS]
    NAMES = DRIVER
    [[DRIVER]]
        IMPLEMENTATION = ensemble_driver

[ensemble_driver]
    CLASS = DRIVER
    SUB_CLASS =
    NAME = EnsembleDriver
    NPROC = 1
    BIN_PATH =
    INPUT_FILES =
    OUTPUT_FILES =
    SCRIPT = $PWD/driver.py
    MODULE =
    # Specifies the template configuration file used for instances
    TEMPLATE = $PWD/template.conf

