# IPS Perlmutter configuration file

#######################################
# Parallel environment
#######################################
MPIRUN = srun
NODE_DETECTION = slurm_env # let it detect nodes
CORES_PER_NODE = 128
PROCS_PER_NODE = 128
SOCKETS_PER_NODE = 2
NODE_ALLOCATION_MODE =  shared

#######################################
# Run-time parameters
#######################################
HOST = localhost

#######################################
# Portal configuration
#######################################
USE_PORTAL = False