# IPS Perlmutter configuration file

#######################################
# Parallel environment
#######################################
MPIRUN = srun
NODE_DETECTION = slurm_env # let it detect nodes
CORES_PER_NODE = 64
PROCS_PER_NODE = 64
SOCKETS_PER_NODE = 2
NODE_ALLOCATION_MODE =  shared

#######################################
# Portal configuration
#######################################
USE_PORTAL = False