SIM_NAME = example_023
SIM_ROOT = $PWD/ENSEMBLES
LOG_FILE = log
LOG_LEVEL = INFO
SIMULATION_MODE = NORMAL

INPUT_DIR = $PWD/input_dir/

USE_PORTAL = True
PORTAL_URL=https://lb.ipsportal.development.svc.spin.nersc.org
# do not commit actual PORTAL_API_KEY value to version control, best to set as an environment variable
#PORTAL_API_KEY=changeme

[PORTS]
    NAMES = DRIVER
    [[DRIVER]]
        IMPLEMENTATION = ensemble_driver

[ensemble_driver]
    CLASS = DRIVER
    SUB_CLASS =
    NAME = EnsembleDriver
    NPROC = 1
    BIN_PATH =
    INPUT_FILES =
    OUTPUT_FILES =
    SCRIPT = $PWD/driver.py
    MODULE =
    # Specifies the template configuration file used for instances
    TEMPLATE = $PWD/template.conf

