SIM_ROOT = $PWD/sim
SIM_NAME = sim
LOG_FILE = sim.log
LOG_LEVEL = DEBUG
SIMULATION_MODE = NORMAL
RUN_COMMENT = From PC
RUN_ID = parent workflow
TAG = tag
INPUT_DIR = $PWD/input_dir/

PORTAL_URL = https://lb.ipsportal.development.svc.spin.nersc.org
#PORTAL_URL = http://localhost:5000
# NOTE: you should not commit the value of PORTAL_API_KEY directly to source control
PORTAL_API_KEY = changeme

STATE_FILES = state.json
STATE_WORK_DIR = $SIM_ROOT/state

[PORTS]
    NAMES = DRIVER

    [[DRIVER]]
        IMPLEMENTATION = driver

[driver]
    CLASS = DRIVER
    SUB_CLASS =
    NAME = ParentWorkflowDriver
    NPROC = 1
    BIN_PATH =
    OUTPUT_FILES =
    INPUT_FILES =
    SCRIPT = $PWD/parent_workflow_driver.py
