name: CI (pip)

on: [push, pull_request, workflow_dispatch]

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: python -m pip install --group dev -e .
      #- name: bandit
      #run: bandit -lll ipsframework/*.py
      - name: ruff-lint
        run: ruff check
      - name: ruff-format
        run: ruff format --check
      - name: codespell
        run: codespell || true

  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "3.11"
          - os: ubuntu-latest
            python-version: "3.12"
          - os: ubuntu-latest
            python-version: "3.13"
          - os: ubuntu-latest
            python-version: "3.14"
          - os: macos-latest
            python-version: "3.12"

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install OpenMPI (Linux)
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          sudo apt-get update
          sudo apt-get install -y openmpi-bin libopenmpi-dev
      - name: Install OpenMPI (macOS)
        if: ${{ startsWith(matrix.os, 'macos') }}
        run: brew install open-mpi
      - name: Install IPS (in develop mode)
        run: python -m pip install --group dev -e .
      - name: testing running IPS (--help)
        run: ips.py --help
      - name: testing showing IPS version (--version)
        run: ips.py --version
      - name: Test with pytest
        run: python -m pytest --cov --cov-report=xml --cov-report=term --timeout=60
        # TODO: remove when tests are fixed
        continue-on-error: true
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        if: ${{ github.ref == 'refs/heads/main' }}

  tests-wsl:
    runs-on: windows-latest

    defaults:
      run:
        shell: wsl-bash {0}

    steps:
      - uses: actions/checkout@v7
      - uses: Vampire/setup-wsl@v7
        with:
          additional-packages:
            python-is-python3
            python3-pip
            python3-venv
            openmpi-bin
            libopenmpi-dev
            # python3-pytest-cov
            # python3-pytest-timeout
            # python3-psutil
      - name: setup VENV for IPS
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --group dev -e .
      - name: testing running IPS (--help)
        run: ips.py --help
      - name: testing showing IPS version (--version)
        run: ips.py --version
      - name: Test with pytest
        run: python -m pytest --cov --timeout=60
        # TODO: remove when tests are fixed
        continue-on-error: true
