name: Merge upstream of ORNL-Fusion/IPS-framework

on:
  push:
    branches:
      - main

jobs:
  merge-upstream:
    runs-on: ubuntu-latest

    steps:
    - name: Merge upstream
      run: |
        curl -X POST -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${{ secrets.MERGE_TOKEN }}" \
        https://api.github.com/repos/ORNL-Fusion/IPS-framework/merge-upstream \
        -d '{"branch":"main"}'
