name: CI

on: [push, pull_request]

jobs:

  static_analysis:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install python testing dependencies
      run: pip install flake8==3.9.2 pylint==2.9.5 bandit==1.7.0 codespell==2.1.0 dask distributed
    - name: flake8
      run: flake8
    - name: pylint
      run: pylint ipsframework
    - name: bandit
      run: bandit -lll ipsframework/*.py
    - name: codespell
      run: codespell

  tests:

    runs-on: ${{ matrix.os }}

    timeout-minutes: 10

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
        dask-version: ['2021.07.1']
        include:
          # same as NERSC Cori module python/3.7-anaconda-2019.10
          - os: ubuntu-latest
            python-version: 3.7
            dask-version: '2.5.2'
          # same as NERSC Cori module python/3.8-anaconda-2020.11
          - os: ubuntu-latest
            python-version: 3.8
            dask-version: '2.30.0'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install python testing dependencies
      run: python -m pip install pytest-cov pytest-timeout psutil
    # There is an issue with click 8 for dask < 2021.05 dask/dask#7658
    - name: Install dask ${{ matrix.dask-version }} with click<8
      if: ${{ matrix.python-version > 3.6 && matrix.dask-version < '2021.05.0' }}
      run: python -m pip install dask==${{ matrix.dask-version }} distributed==${{ matrix.dask-version }} "click<8" msgpack==0.6.2
    - name: Install dask ${{ matrix.dask-version }}
      if: ${{ matrix.python-version > 3.6 && matrix.dask-version >= '2021.05.0' }}
      run: python -m pip install dask==${{ matrix.dask-version }} distributed==${{ matrix.dask-version }}
    - name: Install mpi testing dependencies
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y libopenmpi-dev python3-mpi4py
    - name: Install IPS (in develop mode)
      run: python -m pip install -e .
    - name: testing running IPS (--help)
      run: ips.py --help
    - name: testing showing IPS version (--version)
      run: ips.py --version
    - name: Test with pytest
      run: python -m pytest --cov --verbose --timeout=60
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1

  tests-wsl:

    runs-on: windows-latest

    timeout-minutes: 10

    defaults:
       run:
         shell: wsl-bash {0}

    steps:
    - uses: actions/checkout@v2
    - uses: Vampire/setup-wsl@v1
      with:
          distribution: Ubuntu-20.04
          additional-packages:
              python3-pip
              python-is-python3
    - name: Install python testing dependencies
      run: python -m pip install pytest-cov pytest-timeout psutil dask==2021.07.1 distributed==2021.07.1
    - name: Install IPS (in develop mode)
      run: python -m pip install -e .
    - name: testing running IPS (--help)
      run: ips.py --help
    - name: testing showing IPS version (--version)
      run: ips.py --version
    - name: Test with pytest
      run: python -m pytest --cov --verbose --timeout=60
