name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v7
      - uses: conda-incubator/setup-miniconda@v4
        with:
          miniforge-variant: Miniforge3
          miniforge-version: latest
          channels: conda-forge
          channel-priority: true
          auto-update-conda: true
          environment-file: .github/workflows/conda_env/environment_static_analysis.yml
      #- name: bandit
      #run: bandit -lll ipsframework/*.py
      - name: ruff-lint
        run: ruff check
      - name: ruff-format
        run: ruff format --check
      - name: codespell
        run: codespell || true

  tests:
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "3.11"
            conda_env: "minimal"
          - os: ubuntu-latest
            python-version: "3.12"
            conda_env: "minimal"
          - os: ubuntu-latest
            python-version: "3.13"
            conda_env: "minimal"
          - os: ubuntu-latest
            python-version: "3.14"
            conda_env: "minimal"
          - os: macos-latest
            python-version: "3.12"
            conda_env: "macos"

    steps:
      - uses: actions/checkout@v7
      - uses: conda-incubator/setup-miniconda@v4
        with:
          miniforge-variant: Miniforge3
          miniforge-version: latest
          channels: conda-forge
          channel-priority: true
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: .github/workflows/conda_env/environment_${{ matrix.conda_env }}.yml
      - name: Install IPS (in develop mode)
        run: python -m pip install -e .
      - name: testing running IPS (--help)
        run: ips.py --help
      - name: testing showing IPS version (--version)
        run: ips.py --version
      - name: Test with pytest
        run: python -m pytest --cov --cov-report=xml --cov-report=term --timeout=60
        # TODO: remove when tests are fixed
        continue-on-error: true
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        if: ${{ github.ref == 'refs/heads/main' }}

  tests-wsl:
    runs-on: windows-latest

    defaults:
      run:
        shell: wsl-bash {0}

    steps:
      - uses: actions/checkout@v7
      - uses: Vampire/setup-wsl@v7
        with:
          additional-packages:
            python-is-python3
            python3-pip
            python3-flask
            # python3-pytest-cov
            # python3-pytest-timeout
            # python3-psutil
      - name: setup VENV for IPS
        run: |
          python -m venv .venv
          source .venv/bin/activate
      - name: Install IPS (in develop mode)
        run: python -m pip install --group dev -e .
      - name: testing running IPS (--help)
        run: ips.py --help
      - name: testing showing IPS version (--version)
        run: ips.py --version
      - name: Test with pytest
        run: python -m pytest --cov --timeout=60
        # TODO: remove when tests are fixed
        continue-on-error: true
